---
# tasks file for ansible-role-mcafee-agent

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: item|string not in ansible_facts.packages
  with_items: "{{ packages }}"

- name: "Create software directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/software/mcafee-agent/"
    state: directory

- name: "Check if installer package already exist"
  ansible.builtin.stat:
    path: "/root/software/mcafee-agent/{{ package_name }}"
  register: package

- name: "Download installer package from local repository"
  ansible.builtin.get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/mcafee-agent/"
    validate_certs: no
    mode: '0770'
  when: package.stat.exists != True

- name: "Install package"
  ansible.builtin.command: "./{{ package_name }} -i"
  args:
    chdir: "/root/software/mcafee-agent/"
    creates: /etc/ma.d/ma_environment.conf
